# Sales Data Analysis

## 1. Import Libraries

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

## 2. Load Dataset

In [3]:
sales_df = pd.read_csv("data/sales_data.csv")

## 3. Initial Data Exploration

### 3.1 Dataset Dimensions

In [4]:
rows, columns = sales_df.shape

print(f"Rows: {rows}")
print(f"Columns: {columns}")

Rows: 113036
Columns: 18

### 3.2 Data Types

In [5]:
sales_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 113036 entries, 0 to 113035
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Date              113036 non-null  str
 1   Day               113036 non-null  int64
 2   Month             113036 non-null  str
 3   Year              113036 non-null  int64
 4   Customer_Age      113036 non-null  int64
 5   Age_Group         113036 non-null  str
 6   Customer_Gender   113036 non-null  str
 7   Country           113036 non-null  str
 8   State             113036 non-null  str
 9   Product_Category  113036 non-null  str
 10  Sub_Category      113036 non-null  str
 11  Product           113036 non-null  str
 12  Order_Quantity    113036 non-null  int64
 13  Unit_Cost         113036 non-null  int64
 14  Unit_Price        113036 non-null  int64
 15  Profit            113036 non-null  int64
 16  Cost              113036 non-null  int64
 17  Revenue           113036 non-null  int64
dtypes: int64(9), str(9)
memory usage: 15.5 MB

### 3.3 Missing Values

In [6]:
sales_df.isnull().sum()

Date                0
Day                 0
Month               0
Year                0
Customer_Age        0
Age_Group           0
Customer_Gender     0
Country             0
State               0
Product_Category    0
Sub_Category        0
Product             0
Order_Quantity      0
Unit_Cost           0
Unit_Price          0
Profit              0
Cost                0
Revenue             0
dtype: int64

### 3.4 Duplicate Records

In [8]:
sales_df.duplicated().sum()

np.int64(1000)

### 3.5 Numerical Summary

In [10]:
sales_df.describe().T

,count,mean,std,min,25%,50%,75%,max
Day,113036.0,15.665753,8.781567,1.0,8.0,16.0,23.0,31.0
Year,113036.0,2014.401739,1.272510,2011.0,2013.0,2014.0,2016.0,2016.0
Customer_Age,113036.0,35.919212,11.021936,17.0,28.0,35.0,43.0,87.0
Order_Quantity,113036.0,11.901660,9.561857,1.0,2.0,10.0,20.0,32.0
Unit_Cost,113036.0,267.296366,549.835483,1.0,2.0,9.0,42.0,2171.0
Unit_Price,113036.0,452.938427,922.071219,2.0,5.0,24.0,70.0,3578.0
Profit,113036.0,285.051665,453.887443,-30.0,29.0,101.0,358.0,15096.0
Cost,113036.0,469.318695,884.866118,1.0,28.0,108.0,432.0,42978.0
Revenue,113036.0,754.370360,1309.094674,2.0,63.0,223.0,800.0,58074.0

### 3.6 Numerical Ranges

In [15]:
sales_df.describe().T[['min', 'max']]

                   min      max
Day                1.0     31.0
Year            2011.0   2016.0
Customer_Age      17.0     87.0
Order_Quantity     1.0     32.0
Unit_Cost          1.0   2171.0
Unit_Price         2.0   3578.0
Profit           -30.0  15096.0
Cost               1.0  42978.0
Revenue            2.0  58074.0

### 3.7 Unique Categories

In [34]:
print(f'Count of Unique Product - {sales_df['Product'].nunique()}' )

sales_df['Product'].unique()

sales_df['Product'].value_counts()

Count of Unique Product - 130

Product
Water Bottle - 30 oz.      10794
Patch Kit/8 Patches        10416
Mountain Tire Tube          6816
AWC Logo Cap                4358
Sport-100 Helmet, Red       4220
                           ...
Touring-3000 Blue, 50         58
Mountain-100 Silver, 42       54
Mountain-500 Silver, 48       40
Road-650 Red, 52              32
Mountain-500 Black, 52        22
Name: count, Length: 130, dtype: int64

In [ ]:
print(f'Count of unique Product_Category - {sales_df['Product_Category'].nunique()}')

sales_df['Product_Category'].unique()

sales_df['Product_Category'].value_counts()

Count of unique Product_Category 3

Product_Category
Accessories    70120
Bikes          25982
Clothing       16934
Name: count, dtype: int64

In [33]:
print(f'Count of unique Sub_Category - {sales_df['Sub_Category'].nunique()}')

sales_df['Sub_Category'].unique()

sales_df['Sub_Category'].value_counts()

Count of unique Sub_Category - 17

Sub_Category
Tires and Tubes      33870
Bottles and Cages    15876
Road Bikes           13430
Helmets              12158
Mountain Bikes        8854
Jerseys               6010
Caps                  4358
Fenders               4032
Touring Bikes         3698
Gloves                2686
Cleaners              1802
Shorts                1794
Hydration Packs       1334
Socks                 1122
Vests                  964
Bike Racks             592
Bike Stands            456
Name: count, dtype: int64